services:
  vue_on_rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - bundle_cache:/usr/local/bundle
    env_file: .env
    tty: true
    stdin_open: true
    command: sh -c "bin/webpack-dev-server --host 0.0.0.0 --watch-poll & bin/rails server -b 0.0.0.0"

  database:
    image: postgres:16.4-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  node_modules:
  bundle_cache:
